# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazonURL',
            field=models.URLField(default=b'', null=True),
        ),
    ]
